baseURL = "https://DeepakR19.github.io/devops-blog/"
languageCode = "en-us"
title = "My DevOps Blog"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]

  [[menu.main]]
    name = "ğŸ§ Linux"
    url = "/linux/"
    weight = 1

  [[menu.main]]
    name = "ğŸŒ± Git"
    url = "/git/"
    weight = 2

  [[menu.main]]
    name = "ğŸ” CI/CD"
    url = "/cicd/"
    weight = 3

  [[menu.main]]
    name = "â˜ï¸ Cloud"
    url = "/cloud/"
    weight = 4

  [[menu.main]]
    name = "ğŸ³ Docker"
    url = "/docker/"
    weight = 5

  [[menu.main]]
    name = "â˜¸ï¸ Kubernetes"
    url = "/kubernetes/"
    weight = 6

  [[menu.main]]
    name = "ğŸ— Terraform"
    url = "/terraform/"
    weight = 7

  [[menu.main]]
    name = "âš™ï¸ Ansible"
    url = "/ansible/"
    weight = 8

  [[menu.main]]
    name = "ğŸ§  Scenarios"
    url = "/scenarios/"
    weight = 9
